apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: sathell/discovery-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msv-products
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msv-products
                  key: db_host
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: msv-products
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: msv-products
                  key: database