server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eddyjav/service-configuration-1
          default-label: master
          clone-on-start: true

